apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rfgo66gqi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rfgo66gqi-go 
  name: rfgo66gqi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rfgo66gqi-go 
